### ISSUE TITLE
как пользоваться?

### ISSUE THREAD

**Issue by BoLoSsEvvv** [Adzirii/PartyPurse#1]
не понял как пользоваться, где объяснение?

**Comment by BoLoSsEvvv** [comment]
![Uploading 17200255775040.png…]()

**Comment by BoLoSsEvvv** [comment]
![17200255775040](https://github.com/user-attachments/assets/a6871a30-4d6d-4592-9995-f4053af7ddd4)

**Comment by Adzirii** [comment]
> не понял как пользоваться, где объяснение?

фронтендер женился и не стал заканчивать

**Comment by BoLoSsEvvv** [comment]
> > не понял как пользоваться, где объяснение?
> 
> 
> 
> фронтендер женился и не стал заканчивать

пипец

**Comment by BoLoSsEvvv** [comment]
> > не понял как пользоваться, где объяснение?
> 
> фронтендер женился и не стал заканчивать

а женился то на мужчине надеюсь?
